### ISSUE TITLE
can not restart container after host reboot

### ISSUE THREAD

**Issue by joke-lee** [danchitnis/container-xrdp#1]
after reboot host, i can not start the container any more
![图片](https://user-images.githubusercontent.com/20007497/129155120-f5b04515-e30a-4c67-96d6-e5cf2626bc83.png)

**Comment by danchitnis** [comment]
I think this is expected behaviour. Remember that this is a stateless container, so once you exit the container, you have to run it from scratch again. If you want to save the container state for a later run (not recommended), then perhaps this document can help:
https://stackoverflow.com/questions/44480740/how-to-save-a-docker-container-state
